default_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: GET

default_login:
    path:     /login
    defaults: { _controller: AppBundle:Default:login }
    methods: POST

default_prueba:
    path:     /prueba
    defaults: { _controller: AppBundle:Default:prueba }
    methods: POST