video_new:
    path:     /new
    defaults: { _controller: AppBundle:Video:new }
    methods: POST

video_edit:
    path:     /edit/{videoId}
    defaults: { _controller: AppBundle:Video:edit, videoId:null }
    methods: POST

video_upload_image:
    path:     /upload-image/{videoId}
    defaults: { _controller: AppBundle:Video:upload, videoId:null }
    methods: POST

video_upload_video:
    path:     /upload-video/{videoId}
    defaults: { _controller: AppBundle:Video:upload, videoId:null }
    methods: POST

video_list:
    path:     /list
    defaults: { _controller: AppBundle:Video:videos }
    methods: GET

video_lasts_videos:
    path:     /lasts-videos
    defaults: { _controller: AppBundle:Video:lastsVideos }
    methods: GET

video_detail:
    path:     /detail/{id}
    defaults: { _controller: AppBundle:Video:video, id:null }
    methods: GET

video_search:
    path:     /search/{search}
    defaults: { _controller: AppBundle:Video:search, search:null }
    methods: GET